#!/bin/bash
# SaltGoat Magento Varnish helper
# Usage: saltgoat magetools varnish <enable|disable> <site>

set -euo pipefail

: "${SCRIPT_DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/logger.sh"

ACTION="${1:-}"
SITE="${2:-}"

require_site() {
    if [[ -z "${SITE}" ]]; then
        log_error "请提供站点名称: saltgoat magetools varnish <enable|disable> <site>"
        exit 1
    fi
    if [[ ! -d "/var/www/${SITE}" ]]; then
        log_error "站点目录不存在: /var/www/${SITE}"
        exit 1
    fi
    if [[ ! -f "/etc/nginx/sites-available/${SITE}" ]]; then
        log_error "Nginx 站点配置不存在: /etc/nginx/sites-available/${SITE}"
        exit 1
    fi
}

run_magento() {
    local args=("$@")
    sudo -u www-data -H bash -lc "cd /var/www/${SITE} && php bin/magento ${args[*]}"
}

backup_dir() {
    echo "/etc/nginx/sites-available/.saltgoat-varnish-backups"
}

frontend_snippet() {
    echo "/etc/nginx/snippets/varnish-frontend-${SITE}.conf"
}

backend_conf() {
    echo "/etc/nginx/sites-available/${SITE}-backend"
}

backend_symlink() {
    echo "/etc/nginx/sites-enabled/${SITE}-backend"
}

detect_admin_prefix() {
    local env_file="/var/www/${SITE}/app/etc/env.php"
    if [[ ! -f "$env_file" ]]; then
        echo "admin"
        return
    fi
    sudo -u www-data -H php -r "require '${env_file}'; echo isset(\$config['backend']['frontName']) ? trim(\$config['backend']['frontName']) : 'admin';" 2>/dev/null | tr -dc '[:alnum:]_-'
    echo
}

ensure_backup() {
    local dir file
    dir="$(backup_dir)"
    file="${dir}/${SITE}.conf.orig"
    sudo mkdir -p "$dir"
    if [[ ! -f "$file" ]]; then
        log_info "备份原始 Nginx 配置到 ${file}"
        sudo cp "/etc/nginx/sites-available/${SITE}" "$file"
    fi
}

restore_backup() {
    local file
    file="$(backup_dir)/${SITE}.conf.orig"
    if [[ -f "$file" ]]; then
        log_info "恢复原始 Nginx 配置"
        sudo cp "$file" "/etc/nginx/sites-available/${SITE}"
    else
        log_warning "未找到备份文件，跳过恢复"
    fi
}

replace_include() {
    local target="$1"
    sudo python3 - "$SITE" "$target" <<'PY'
import sys, pathlib, re
site = sys.argv[1]
target = sys.argv[2]
path = pathlib.Path("/etc/nginx/sites-available") / site
data = path.read_text(encoding="utf-8")
snippet_line = f'    include {target};'
if snippet_line in data:
    sys.exit(0)
sample_pattern = re.compile(r'^\s*include\s+/var/www/' + re.escape(site) + r'/nginx\.conf\.sample;\s*$', re.MULTILINE)
if sample_pattern.search(data):
    data = sample_pattern.sub(snippet_line, data, count=1)
else:
    mage_pattern = re.compile(r'^\s*set\s+\$MAGE_ROOT.*$', re.MULTILINE)
    match = mage_pattern.search(data)
    if match:
        idx = match.end()
        data = data[:idx] + "\n" + snippet_line + data[idx:]
    else:
        data += "\n" + snippet_line + "\n"
path.write_text(data, encoding="utf-8")
PY
}

restore_include_sample() {
    sudo python3 - "$SITE" <<'PY'
import sys, pathlib, re
site = sys.argv[1]
path = pathlib.Path("/etc/nginx/sites-available") / site
data = path.read_text(encoding="utf-8")
snippet_pattern = re.compile(r'^\s*include\s+/etc/nginx/snippets/varnish-frontend-' + re.escape(site) + r'\.conf;\s*$', re.MULTILINE)
if snippet_pattern.search(data):
    data = snippet_pattern.sub(f'    include /var/www/{site}/nginx.conf.sample;', data, count=1)
path.write_text(data, encoding="utf-8")
PY
}

write_frontend_snippet() {
    local snippet admin_prefix extra_admin_block
    admin_prefix="$(detect_admin_prefix)"
    [[ -z "$admin_prefix" ]] && admin_prefix="admin"
    snippet="$(frontend_snippet)"
    extra_admin_block=""
    if [[ "$admin_prefix" != "admin" ]]; then
        read -r -d '' extra_admin_block <<'EOADMIN'
location ^~ /admin/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering on;
    proxy_buffers 64 256k;
    proxy_buffer_size 512k;
    proxy_busy_buffers_size 512k;
    proxy_temp_file_write_size 512k;
    proxy_max_temp_file_size 0;
    proxy_cache_bypass \$http_cache_control;
}

EOADMIN
    fi
    sudo tee "$snippet" >/dev/null <<EOF
# Auto-generated by SaltGoat varnish enable
proxy_hide_header Content-Security-Policy;
proxy_hide_header Content-Security-Policy-Report-Only;
add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://assets.adobedtm.com; style-src 'self' 'unsafe-inline'" always;
add_header Content-Security-Policy-Report-Only "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://assets.adobedtm.com; style-src 'self' 'unsafe-inline'" always;
location ^~ /.well-known/acme-challenge/ {
    root /var/www/${SITE}/pub;
}

location ^~ /${admin_prefix}/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering on;
    proxy_buffers 64 256k;
    proxy_buffer_size 512k;
    proxy_busy_buffers_size 512k;
    proxy_temp_file_write_size 512k;
    proxy_max_temp_file_size 0;
    proxy_cache_bypass \$http_cache_control;
}

$extra_admin_block

location ^~ /customer/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering off;
}

location ^~ /rest/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering off;
}

location ^~ /graphql {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering off;
}

location ^~ /page_cache/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering off;
}

location / {
    proxy_pass http://127.0.0.1:6081;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_http_version 1.1;
    proxy_set_header Connection keep-alive;
    proxy_buffering on;
    proxy_buffers 64 256k;
    proxy_buffer_size 512k;
    proxy_busy_buffers_size 512k;
    proxy_temp_file_write_size 512k;
    proxy_max_temp_file_size 0;
    proxy_cache_bypass \$http_cache_control;
}
EOF
}

write_backend_config() {
    local backend
    backend="$(backend_conf)"
    sudo tee "$backend" >/dev/null <<EOF
# Auto-generated by SaltGoat varnish enable
server {
    listen 127.0.0.1:8080;
    server_name ${SITE};

    set \$MAGE_ROOT /var/www/${SITE};
    include /var/www/${SITE}/nginx.conf.sample;
}
EOF
    sudo ln -sf "$backend" "$(backend_symlink)"
}

remove_backend_config() {
    local backend link
    backend="$(backend_conf)"
    link="$(backend_symlink)"
    if [[ -L "$link" ]]; then
        sudo rm -f "$link"
    fi
    if [[ -f "$backend" ]]; then
        sudo rm -f "$backend"
    fi
}

nginx_reload() {
    if ! sudo nginx -t >/tmp/nginx-test.log 2>&1; then
        log_error "nginx -t 失败："
        cat /tmp/nginx-test.log
        exit 1
    fi
    sudo systemctl reload nginx
    log_success "Nginx 已重新加载"
}

apply_varnish_state() {
    log_info "应用 Varnish Salt 状态"
    sudo salt-call --local state.apply optional.varnish >/tmp/varnish-state.log 2>&1 || {
        log_error "应用 optional.varnish 状态失败，详情："
        cat /tmp/varnish-state.log
        exit 1
    }
    sudo systemctl enable --now varnish >/dev/null 2>&1 || true
    sudo systemctl restart varnish
}

configure_magento_varnish() {
    log_info "更新 Magento 缓存配置为 Varnish"
    run_magento config:set system/full_page_cache/caching_application 2 >/dev/null
    run_magento config:set system/full_page_cache/varnish/backend_host 127.0.0.1 >/dev/null
    run_magento config:set system/full_page_cache/varnish/backend_port 8080 >/dev/null
    run_magento config:set system/full_page_cache/varnish/access_list 127.0.0.1 >/dev/null
    run_magento cache:flush >/dev/null
}

configure_magento_builtin() {
    log_info "恢复 Magento 缓存为 Built-in"
    run_magento config:set system/full_page_cache/caching_application 1 >/dev/null
    run_magento cache:flush >/dev/null
}

enable_varnish() {
    log_highlight "为站点 ${SITE} 启用 Varnish"
    ensure_backup
    write_frontend_snippet
    replace_include "$(frontend_snippet)"
    write_backend_config
    nginx_reload
    apply_varnish_state
    configure_magento_varnish
    log_success "站点 ${SITE} 已启用 Varnish（前端 Nginx -> Varnish -> backend Nginx/PHP）"
}

disable_varnish() {
    log_highlight "为站点 ${SITE} 停用 Varnish"
    restore_backup
    restore_include_sample
    sudo rm -f "$(frontend_snippet)"
    remove_backend_config
    nginx_reload
    configure_magento_builtin
    sudo systemctl disable --now varnish >/dev/null 2>&1 || true
    log_success "站点 ${SITE} 已恢复为原始 Nginx/PHP 模式"
}

case "${ACTION}" in
    enable)
        require_site
        enable_varnish
        ;;
    disable)
        require_site
        disable_varnish
        ;;
    ""|help|--help|-h)
        cat <<EOF
用法: saltgoat magetools varnish <enable|disable> <site>

示例:
  sudo saltgoat magetools varnish enable bank
  sudo saltgoat magetools varnish disable bank
EOF
        ;;
    *)
        log_error "未知操作: ${ACTION}，支持: enable, disable"
        exit 1
        ;;
esac
